DROP DATABASE IF EXISTS game_db;
CREATE DATABASE game_db;

CREATE TABLE players
(
	id int NOT NULL AUTO_INCREMENT,
	name varchar(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE scores
(
	id in NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	score INT(10) NOT NULL,
	PRIMARY KEY (id)
);