<<<<<<< HEAD
DROP DATABASE IF EXISTS gamedb;
CREATE DATABASE gamedb;
=======
DROP DATABASE IF EXISTS game_db;
CREATE DATABASE game_db;

CREATE TABLE players
(
	id int NOT NULL AUTO_INCREMENT,
	name varchar(255) NOT NULL,
	PRIMARY KEY (id)
);
>>>>>>> aa0f46d237bf61d526b2f99de6e19bed7422acf6

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;
